### PR TITLE
ZDAG fixes + miner code related to input conflicts

### LINKED ISSUE #391: Input conflict causing miners to not be able to miner
An asset allocation is allowed to propagate inputs that are in conflict exactly one time (the first time) and the miner code usually would take care of taking these out as they would have typically been double-spend asset attempts (balance overflows) however in the case of someone just spending regular sys or asset within bounds twice with the same input, the miner code isn'y picking up on this particular scenario.

### PR DESCRIPTION
**Pull request by sidhujag**
fixes #391

- miner code updated to avoid conflicting inputs related to asset allocations (on conflict is allowed per mempool rules if it is an asset allocation tx dbl spend attempt)
- ZDAG status' updated to reflect for input conflict detection across all ancestors in mempool

Miners were not able to mine a block due to conflicting inputs caused by inadvertent test where input was relayed by nodes based on correct functioning of our protocol to relay dbl spends related to asset allocation.

To reproduce:
1) Send regular sys or asset with input A
2) Send asset with input A
3) All nodes will propogate both transactions due to mempool policy
4) Miner will have issue with mining because it checks for balance overflow on dbl spend attempts in mempool across asset transactions but is missing a check related to conflicting inputs related to asset transactions

Fix:
1) Add mempool conflicting input detection prior to mining block along with the balance overflows checks currently in the mempool code for syscoin consensus.
2) Update ZDAG protocol status to correctly detect for issues when inputs are conflicting, simply don't accept that transaction in point of sale, it is potentially not going to be mined.

### CODE REVIEW

**Review by willyko — DISMISSED** [review]
ACK

**Review by willyko — DISMISSED** [review]

**Review by Keyare — APPROVED** [review]
Ack

**Review by willyko — APPROVED** [review]

File: src/miner.h [hunk 1]
```diff
@@ -87,7 +87,8 @@ struct CompareTxIterByAncestorCount {
     {
         if (a->GetCountWithAncestors() != b->GetCountWithAncestors())
             return a->GetCountWithAncestors() < b->GetCountWithAncestors();
-        return CTxMemPool::CompareIteratorByHash()(a, b);
+        // SYSCOIN
+        return a->GetTime() < b->GetTime();
     }
```
Comment (sidhujag) [inline src/miner.h:92]: This is a critical improvement by removing ordering by time in graph.cpp we simply modify the comparator to return time ordering if ancestor counts are equal, we want ancestor ordering to be higher prescedence anyways followed by time so this shoudl work for us.
