### PR TITLE
Fixes #406

### LINKED ISSUE #406: New masternode commands crashes syscoind when entered without argument
Issue most likely due to ported commands being non-standard to the bitcoin's new rpc format

**Expected behavior**
```
$ syscoin-cli bls
error code: -1
error message:
bls
Set of commands to execute BLS related actions.
To get help on individual commands, use "help bls command".

Arguments:
1. "command"        (string, required) The command to execute

Available commands:
  generate          - Create a BLS secret/public key pair
  fromsecret        - Parse a BLS secret key and return the secret/public key pair

Result:
null    (json null)
```
```
$ syscoin-cli protx
error code: -1
error message:
protx
Set of commands to execute ProTx related actions.
To get help on individual commands, use "help protx command".

Arguments:
1. "command"        (string, required) The command to execute

Available commands:
  register          - Create and send ProTx to network
  register_fund     - Fund, create and send ProTx to network
  register_prepare  - Create an unsigned ProTx
  register_submit   - Sign and submit a ProTx
  list              - List ProTxs
  info              - Return information about a ProTx
  update_service    - Create and send ProUpServTx to network
  update_registrar  - Create and send ProUpRegTx to network
  revoke            - Create and send ProUpRevTx to network
  diff              - Calculate a diff and a proof between two masternode lists

Result:
null    (json null)
```

**Actual behavior**
```
$ syscoin-cli bls
error: Could not connect to the server 127.0.0.1:18370 (error code 1 - "EOF reached")

Make sure the syscoind server is running and that you are connecting to the correct RPC port.
```
```
$ syscoin-cli protx
error: Could not connect to the server 127.0.0.1:18370 (error code 1 - "EOF reached")

Make sure the syscoind server is running and that you are connecting to the correct RPC port.
```

**To reproduce**

`syscoin-cli bls`
`syscoin-cli masternode`
`syscoin-cli protx`

### PR DESCRIPTION
**Pull request by willyko**
Fixes #406 
Also added `syscoin-cli help command [subcommand]`

### CODE REVIEW

File: src/rpc/server.cpp [hunk 1]
```diff
@@ -100,6 +100,11 @@ std::string CRPCTable::help(const std::string& strCommand, const JSONRPCRequest&
         jreq.strMethod = strMethod;
         try
         {
+            if (!strSubCommand.empty()) {
```
Comment (sidhujag) [inline src/rpc/server.cpp:105]: // SYSCOIN

File: src/rpc/server.cpp [hunk 2]
```diff
@@ -76,7 +76,7 @@ void RPCServer::OnStopped(std::function<void ()> slot)
     g_rpcSignals.Stopped.connect(slot);
 }
 
-std::string CRPCTable::help(const std::string& strCommand, const JSONRPCRequest& helpreq) const
+std::string CRPCTable::help(const std::string& strCommand, const std::string& strSubCommand, const JSONRPCRequest& helpreq) const
```
Comment (sidhujag) [inline src/rpc/server.cpp:80]: // SYSCOIN

File: src/rpc/server.cpp [hunk 3]
```diff
@@ -132,12 +137,14 @@ std::string CRPCTable::help(const std::string& strCommand, const JSONRPCRequest&
 
 UniValue help(const JSONRPCRequest& jsonRequest)
 {
-    if (jsonRequest.fHelp || jsonRequest.params.size() > 1)
+    if (jsonRequest.fHelp || jsonRequest.params.size() > 2)
```
Comment (sidhujag) [inline src/rpc/server.cpp:143]: // SYSCOIN
